import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { DynamicContextProvider, DynamicWagmiConnector, EthereumWalletConnectors, ZeroDevSmartWalletConnectors } from "../lib/dynamic"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <DynamicContextProvider
            settings={{
                environmentId: process.env.NEXT_PUBLIC_DYNAMIC_ENV_ID!,
                walletConnectors: [
                    EthereumWalletConnectors,
                    ZeroDevSmartWalletConnectors
                ],
            }}
        >
            <DynamicWagmiConnector>
                <body className={inter.className}>{children}</body>
            </DynamicWagmiConnector>
        </DynamicContextProvider>
        </html>
    )
}
